version: "2"
networks:
  stintmaster:

services:
  db:
    image: postgres:${POSTGRES_TAG}
    container_name: stintmaster-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PWD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - stintmaster-db:/var/lib/postgresql/data

volumes:
  stintmaster-db: